#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
signin_user:
    path: /authorize/signin

home:
    path: /home
    controller: App\Controller\HomePage::home

mailsent:
    path: /mailsent
    controller: App\Controller\UserConfirmation::indexAction

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

authorize:
    path: /authorize
    controller: App\Controller\UserController::show