#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
signin_user:
    path: /authorize/signin

home:
    path: /home
    controller: App\Controller\HomePage::home


authorize:
    path: /authorize
    controller: App\Controller\UserController::show